# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64

image: Visual Studio 2015

init:
  - npm config set msvs_version 2015 # we need this to build `pty.js`

cache:
  - node_modules

install:
  - ps: Install-Product node 6 x64
  - set CI=true
  - npm -g install npm@latest
  - npm install

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm run test

on_success:
  - npm run dist
  - ps: ls .\dist\win\*.exe | % { Push-AppveyorArtifact $_.FullName }
