# https://github.com/sindresorhus/appveyor-node/blob/master/appveyor.yml

environment:
  matrix:
    - platform: x64

image: Visual Studio 2015

init:
  - yarn config set msvs_version 2015 # we need this to build `pty.js`

install:
  - ps: Install-Product node 8 x64
  - set CI=true
  - yarn

build: off

matrix:
  fast_finish: true

shallow_clone: true

test_script:
  - node --version
  - yarn --version
  - yarn run test

on_success:
  - IF %APPVEYOR_REPO_BRANCH%==canary cp build\canary.ico build\icon.ico
  - yarn run dist
  - ps: Get-ChildItem .\dist\squirrel-windows\*.exe | % { Push-AppveyorArtifact $_.FullName }
