name: Comment e2e test screenshots on PR
on:
  workflow_run:
    workflows: ['Node CI']
    types:
      - completed
jobs:
  e2e_comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Dump Workflow run info from GitHub context
        env:
          WORKFLOW_RUN_INFO: ${{ toJSON(github.event.workflow_run) }}
        run: echo "$WORKFLOW_RUN_INFO"
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: nodejs.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: e2e
      - name: Get PR number
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: nodejs.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: pr_num
      - name: Read the pr_num file
        id: pr_num_reader
        uses: juliangruber/read-file-action@v1.1.7
        with:
          path: ./pr_num.txt
      - name: List images
        run: ls -al
      - name: Upload images to imgur
        id: upload_screenshots
        uses: devicons/public-upload-to-imgur@v2.2.2
        with:
          path: ./*.png
          client_id: ${{ secrets.IMGUR_CLIENT_ID }}
      - name: Comment on the PR
        uses: jungwinter/comment@v1
        env:
          IMG_MARKDOWN: ${{ join(fromJSON(steps.upload_screenshots.outputs.markdown_urls), '') }}
          MESSAGE: |
            Hi there,
            Thank you for contributing to Hyper!
            You can get the build artifacts from [here](https://nightly.link/{1}/actions/runs/{2}).
            Here are screenshots of Hyper built from this pr.
            {0}
        with:
          type: create
          issue_number: ${{ steps.pr_num_reader.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ format(env.MESSAGE, env.IMG_MARKDOWN, github.repository, github.event.workflow_run.id) }}
      - name: Hide older comments
        uses: kanga333/comment-hider@v0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leave_visible: 1
          issue_number: ${{ steps.pr_num_reader.outputs.content }}
